services:
  # 🗄️ Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    ports:
      - "3307:3306"
    networks:
      - primac

  # 🗄️ Base de datos PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - primac
    volumes:
      - ./databases/proyecto_postgresql/init:/docker-entrypoint-initdb.d

  # 🗄️ Base de datos Cassandra 

  # 🔁 Servicio de Ingesta
  ingesta:
    build:
      context: ./services/ingesta
      dockerfile: Dockerfile
    container_name: ingesta
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - ENV_MODE=${ENVIRONMENT}
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET=${S3_BUCKET}
    env_file:
      - .env
    networks:
      - primac

  # 📊 API Analítica
  analytics_api:
    build:
      context: ./services/data_science_api
      dockerfile: Dockerfile
    container_name: analytics_api
    depends_on:
      - mysql
      - postgres
      #- cassandra_test
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - primac

  # 🌐 Balanceador de carga (Nginx)
  load_balancer:
    image: nginx:latest
    container_name: nginx_lb
    depends_on:
      - analytics_api
    ports:
      - "80:80"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - primac

#volumes:
 # cassandra_data:

networks:
  primac:
    external: true
